basic.showIcon(IconNames.Happy)
basic.forever(function () {
    // 控制小车的流水灯
    cbit_小车类.RGB_Car_Program().setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(1, neopixel.colors(NeoPixelColors.Orange))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(2, neopixel.colors(NeoPixelColors.Yellow))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(0, neopixel.colors(NeoPixelColors.Green))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(1, neopixel.colors(NeoPixelColors.Blue))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(2, neopixel.colors(NeoPixelColors.Violet))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(0, neopixel.colors(NeoPixelColors.Purple))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(1, neopixel.colors(NeoPixelColors.White))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
    cbit_小车类.RGB_Car_Program().setPixelColor(2, neopixel.colors(NeoPixelColors.Indigo))
    cbit_小车类.RGB_Car_Program().show()
    basic.pause(500)
    cbit_小车类.RGB_Car_Program().clear()
})
